# atención! unfinished draft!!!!

In [23]:
# Python Standard Library imports
from pathlib import Path

# third-party imports
from astropy.io import fits
import matplotlib.pyplot as plt
import numpy as np

## arrays

Arrays are one of the most important data structures in scientific programming, and, for that matter, practical mathematics more generally -- they are a basic pattern used in many systems and cultures. Computers are very good at working with them, so knowing how to manipulate them effectively is extremely powerful. If you are reading this, it is entirely possible you have extensive experience with array data. Things may be different in Python than other languages, though, so we recommend not skipping it.

### what is an array?

Basically, an array is simply a regular grid of 'elements', which are often but not always numbers. It can be 1-D, 2-D, 3-D, or even more. A 1-D array is a lot like a list. 

You can access elements in an array by coordinates, which means that they work like coordinate spaces. This is *very* useful for scientific programming. You can also perform mathematical operations on an entire array at once, which is both convenient and typically much faster than performing the same operations on each element one-by-one.

(footnote for the mathematically inclined): an array is *not* a vector, matrix, or tensor, but it can be used to *represent* a vector, matrix, or tensor. 

### how do you work with arrays in Python?

`numpy` is the most common library for creating and manipulating arrays. Most scientific programs use `numpy` at some point, partly because many other libraries use it 'under the hood'. A very important point is that raster images (images made up of pixels, as opposed to vector images) can always be converted to and from arrays, which means that arrays let you do very powerful image manipulation. Let's start with a very quick introduction to the most important parts of the `numpy` library.

In [120]:
# make a 4x4 triangular array
triangle = np.tri(4)
triangle

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [121]:
# you can access single elements of an array by entering their coordinates in
# slice [] notation -- much like a Python list but with possible extra dimensions.
# for a 2-D array, the row (y-axis) always goes first, then the column (x-axis).
# you get exactly the elements you specify, which means that if you don't enter
# a number for every dimension, you can pick more than one element at a time.
# for instance, [0] means 'all the elements with 0-coordinate on the y-axis', 
# or, in other words, the first row.
# [:, 0] (':' is numpy's placeholder) means 'all the elements with 0-coordinate 
# on the x-axis', and will give you the first column.
# If you specify a number for every dimension, you can get just a single element:
# [0, 0] means 'the number in the upper-left corner'.
triangle[0], triangle[:, 0], triangle[0, 0]

(array([1., 0., 0., 0.]), array([1., 1., 1., 1.]), 1.0)

In [122]:
# you can also specify ranges. for instance, [0:2, 0:2] means 'give me the square in the 
# upper-left corner of size (2, 2)'.
triangle[0:2, 0:2]

array([[1., 0.],
       [1., 1.]])

In [123]:
# 'shape', in numpy, means how many elements an array has along each of its dimensions.
# it's important to know an array's shape for a variety of reasons, but one of them
# is to know exactly how much there is to slice. you can access this with .shape:
triangle.shape

(4, 4)

In [124]:
# that means that this will throw an error -- remember that Python is 0-indexed!
triangle[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [125]:
# slicing doesn't only give you elements. you can also use it to set elements. if you
# do the same things, but add an assignment ('='), you can set all the values to a number --
# or even to the contents of another array, if it's the right size.
# this will set all the elements of the first row to 2:
triangle[0] = 2
triangle

array([[2., 2., 2., 2.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [126]:
# if you do an arithmetic operation on an array with a scalar (like a single number),
# it will apply that operation to every element of the array. Unlike slice assignment,
# this does not modify the array in place unless you use a special operator. It returns 
# a copy, leaving the original array unchanged. For instance, to get a copy of the array
# with every element doubled:
double = triangle * 2
double

array([[4., 4., 4., 4.],
       [2., 2., 0., 0.],
       [2., 2., 2., 0.],
       [2., 2., 2., 2.]])

In [127]:
# doing arithmetic using two arrays performs the operation elementwise -- in other words,
# on 'matching' elements of each array. so if we flip double along the x-axis...:
double = np.flip(double, axis=1)
double

array([[4., 4., 4., 4.],
       [0., 0., 2., 2.],
       [0., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [128]:
# and then multiply it by triangle...
double * triangle

array([[8., 8., 8., 8.],
       [0., 0., 0., 0.],
       [0., 2., 2., 0.],
       [2., 2., 2., 2.]])

In [129]:
# this doesn't work if you try to multiply two arrays without matching shapes
# (unless you slice them correctly first!):
three = np.full((3, 3), 3)
three

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [130]:
# so this will throw an error...
three * triangle

ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

In [131]:
# but this won't.
three * triangle[0:3, 0:3]

array([[6., 6., 6.],
       [3., 3., 0.],
       [3., 3., 3.]])

In [132]:
# you can even do assignment like this! this will multiply the upper-left 
# 3x3 square of triangle by 3, in-place:
triangle[0:3, 0:3] = three * triangle[0:3, 0:3]
triangle

array([[6., 6., 6., 2.],
       [3., 3., 0., 0.],
       [3., 3., 3., 0.],
       [1., 1., 1., 1.]])

In [170]:
# finally, you can also slice an array _with_ another array. this can get complicated
# fast: numpy calls it 'fancy indexing' for a reason. however, there are a lot of very 
# simple ways to use it. the most common one is to just
# select all the elements of an array that meet some condition. 
# for instance, this means 'pick all the elements of triangle that are less than 3':
triangle[triangle < 3]

array([2., 0., 0., 0., 1., 1., 1., 1.])

### loading images

Ok, intro examples over; let's take a look at something more practical. We'll load a FITS image into memory using `astropy.io.fits` and look at some basic ways to use it.

In [28]:
# TODO: placeholder image

# FITS files consist of multiple header-data units, or HDUs. Each HDU
# includes a header area containing metadata and a data area containing,
# unsurprisingly, data. This data can be an array or a table. In this case,
# all HDUs are arrays. astropy.io.fits loads FITS files into an HDUList
# object, which in most cases can simply be treated as a Python list with
# some extra useful methods, like .info().
hdul = fits.open('placeholder_images/e23456-nd-t0060-b00-f0008-r.fits')
hdul.info()

Filename: placeholder_images/e23456-nd-t0060-b00-f0008-r.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   ()      
  1  COMPRESSED_IMAGE    1 CompImageHDU    111   (3065, 3099)   float32   
  2  COMPRESSED_IMAGE    1 CompImageHDU    110   (3065, 3099)   uint8   
  3  COMPRESSED_IMAGE    1 CompImageHDU    110   (3065, 3099)   uint8   


In [32]:
# As you can see from the () dimensions entry, HDU 0 contains no actual
# data -- it's a placeholder to help organize the rest of the file.
# HDU 1, however, contains an actual array. Let's go ahead and get the
# data from it:
hdu = hdul[1]
image = hdu.data
image

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### exploring arrays

As we saw earlier, the representation `numpy` provides for arrays is excellent for small arrays. Unfortunately, as we can see here, for large arrays, it doesn't really tell you much except the data type **todo: should we have a section on data types?** and what's in the corners. Fortunately, Python offers many tools for summarizing and visualizing arrays. 

#### dealing with nonfinite values

Before we start exploring, we need to deal with the fact that lots of scientific data -- including this image -- contain 'nonfinite' values: `nan` (not-a-number, sometimes called 'null', used for missing or invalid entries), `inf` (infinity), and `-inf` (negative infinity). This means many statistical tools will fail on them out of the box: what, after all, is the mean of 2, 3, and not-a-number? There are several ways to work with data despite nonfinite values. The most powerful tool `numpy` provides is the masked array, which allows you to ignore specific elements and work with the array just like you would otherwise. A caveat: not all libraries 'respect' masked arrays, so you may have to do fancier tricks when working with some tools. However, many do. We'll show a common trick for dealing with libraries that don't a little further down.

In [133]:
# np.mean does not provide a useful result on the original array:
np.mean(image)

inf

In [134]:
# however, if we construct an array that masks all nonfinite elements, we're in business:
image = np.ma.masked_invalid(image)
np.mean(image)

0.16424812902797892

In [171]:
# let's go ahead and also mask everything below 0 (0 is valid minimum for this image).
# the mask is just an array of boolean (True/False) values, and you can slice and assign
# it just like any other array. we'll use the fancy indexing trick from above:
image.mask[image < 0] = True

#### summarizing arrays

`numpy` offers many built-in tools that are good for simply describing arrays as well as performing mathematical operations. Commonly-useful ones include `std` (standard deviation), `mean`, and `median`. We just looked at `mean`. Let's look at the others.

In [172]:
(
    np.std(image), 
    # using the version from the np.ma namespace because of a little glitch in core numpy
    np.ma.median(image)
)

(8.692995263719943, 0.0)

In [173]:
# these can also be used along an individual axis. for example, if you'd like the mean of every column:
np.mean(image, axis=0)

masked_array(data=[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
             mask=[False, False, False, ..., False, False, False],
       fill_value=1e+20)

#### outside of numpy

For really serious statistical work, it's often useful to turn to `scipy.stats`, which has a wide range of useful tools. `scipy.describe` is great for getting a bunch of basic descriptive statistics at once, *usually*...

In [174]:
from scipy import stats
stats.describe(image)

DescribeResult(nobs=3099, minmax=(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)), mean=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), variance=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), skewness=array([nan, nan, nan, ..., nan, nan, nan], dtype=float32), kurtosis=array([nan, nan, nan, ..., nan, nan, nan], dtype=float32))

In [175]:
# hmmm...that's a lot of nans, and it worked along only one axis, which probably isn't what 
# we wanted. here's a little trick for getting just the unmasked elements of an array, 
# 'raveled' into a single dimension:
valid = image[~image.mask]
stats.describe(valid)

DescribeResult(nobs=9498403, minmax=(0.0, 14406.83), mean=0.16424856, variance=75.56810793146103, skewness=1009.0404376895506, kurtosis=1315403.501804762)

### visualizing arrays

Since many arrays are images, we often want to simply *look* at them. This, of course, can even be useful for arrays that _aren't_ exactly images. There are many ways to do this, but the `imshow` function from `matplotlib.pyplot` is one of the most straightforward: it simply plots a 1D, 2D, or 3D array on a grid. Let's use it to take a look at the image we just opened -- although the results may not be satisfying at first.

In [176]:
plt.imshow(image)

In [177]:
# Unfortunately, plt.imshow, by default, applies a linear 'stretch' to the image. Because the range
# of values in this image are so wide, it doesn't look like much at all -- almost everything is at the
# lower extreme of the color scale.
# let's write a little function that uses numpy to range-clip the image so we can look at it more clearly.

def std_clip(array, sigma=1):
    # find the mean and standard deviation of the array
    mean, std = np.mean(array), np.std(array)
    # restrict the bounds of the array to (mean - sigma * std, mean + sigma * std)
    return np.clip(array, mean - sigma * std, mean + sigma * std)

clipped = std_clip(image)
plt.imshow(clipped)

In [180]:
# because we made sigma variable, we can modify the stretch however we like.
# if we'd like a brighter (but noisier) image:
really_clipped = std_clip(image, sigma=0.25)
plt.imshow(really_clipped)

In [181]:
# slicing works very well on arrays considered as images. for instance, you can use
# it to take a 'cutout' from an image to look at a portion in detail:
plt.imshow(clipped[1000:1200, 1000:1200])

## tables
Tables are basically arrays.

### Ok, but what is a table, really?
A table is _like_ an array, with the following differences:
* 'Table' implies 2-D: it has rows and columns and nothing else.
* The columns of a table are also called 'fields', and have
    *meanings* that are distinct from one another: for instance, a table created from a radiometer 
    on a satellite might have fields representing time, latitude, longitude, and brightness temperature;
    individual rows would represent individual observations.
    * This is different from arrays, where, in general, every element has a roughly equivalent *meaning*, but in a different *place*.
* A table can have more than one data type: for instance, a star catalog might have a field representing
    right ascension in 64-bit floating-point numbers, and a field representing star names as strings.
* **todo: maybe not necessary here** A table also generally has an 'index', which can be 
    a numerical series that simply corresponds to row number, but can be something else
    entirely -- for instance, a table of personnel data might be indexed by employee ID number.

Like arrays, tables are of ancient origin and found in many forms in many contexts, but computers really like to work with them. Tables are even more widely used than arrays in general-purpose computing. Common examples include spreadsheets and SQL databases. The world runs on tables.

### Tabular file formats

#### Broad categories: binary vs. text
Tables can be stored in many formats. The two major _categories_ of format are binary and text tables. Text table formats store values as human-readable strings, like:

| RA | DEC |
| ------ | ----- |
| 17.222 | -12.301 |
| 17.223 | -12.311 |
| 17.222 | -12.323 |

These sorts of tables are relatively easy to look at and manipulate in spreadsheet programs or text editors -- unless they get so big that the program will refuse to load them!

By contrast, binary table formats store values as raw bytes. The number of bytes per entry depends on the underlying data type. They are poorly human-readable, but tend to use less disk space and be quicker to load than text tables. As 32-bit floating point numbers expressed in bytes, the preceding table might look like:
| | |
|-|-|
| \xa8\xc6\x89 | \xe5\xd0D\xc1 |
| \xb4\xc8\x89A | \xe5\xd0D\xc1 |
| \xa8\xc6\x89 | \x02+E\xc1 |

This is about 50% smaller in terms of data volume than the text version, but most people are not going to get much out of just _looking_ at it, and trying to manipulate it by copy-pasting would be fruitless. To use it, you need to load it into software that will translate it into meaningful numbers.

Some binary table formats simply contain encoded values. Other formats embed metadata along with the values (for instance, cell colors in an Excel file). These formats tend to be harder to read.

The upshot of all this is that really large tables -- tables that you wouldn't be able to visually scan, or maybe even successfully load, in a spreadsheet or text editor -- should almost always be stored in binary formats. Small tables are fine to store as text. If you're only planning to use them as intermediate data, though, small tables might also just as well be binary.

#### Characteristics of some specific formats
There are many, many tabular data formats. This is not an exhaustive list, but here are some common formats you are likely to encounter in planetary science and astronomy:

**DSV (delimiter-separated value)**

DSV is a family of text table formats that place each row on a separate line, and separates columns with a special delimiter character, usually a comma or a tab (a tab is represented by '\t' in most programming languages). Comma-separated tables are often called CSV, and tab-separated TSV. This is a CSV table:
```
satellite,1.002,-379,True
unknown,1.547,-22,False
```
Common file extensions for DSV files are .csv, .tsv, .txt, and .tab, but there are many others.


**FWF (fixed-width file)**

FWF is a text table format that places each row on a separate line, and separates columns by defining a specific 'width' -- number of characters -- for each column. These columns may also have whitespace 'padding' to make them easier to read (and for programs to figure out how to parse them if they don't have the definition available). FWF files were traditionally easier for programs to read than DSV files, but this is no longer true. In general, we recommend choosing DSV formats over FWF, because the delimiters make it easier for a wider variety of programs to parse them, they are usually a little smaller (because not every row has to be the same width), and you are less likely to make mistakes if you edit them manually. This is a fixed-width version of the DSV table above:
```
satellite 1.002 -379 True 
unknown   1.547 -22  False
```
.tab and .txt are common file extensions for FWF, but, like DSV, providers often exercise creativity.


**Excel (and other spreadsheet formats)**

Spreadsheet files are generally binary tables with embedded metadata that allow spreadsheet programs to retain formatting like fonts, cell colors, and sheet breaks. These are usually *proprietary* formats: although they can be reverse-engineered, the makers of the software do not publish specifications for them, and they are subject to change between software versions. This means that they are poorly portable and not very future-proof. For these reasons, we do not recommend exchanging scientific data in spreadsheet formats, and most spreadsheet software can easily export data in standard formats like CSV. Most spreadsheet formats have extensions that indicate the specific software used to produce them: for instance, Excel uses .xlsx or .xls.

**FITS**

FITS files, which were invented for astronomy but have seen widespread adoption in other scientific disciplines, can contain either binary or text tables (although FITS text tables are rarely used in practice). Because FITS files, as we discussed earlier, can have multiple HDUs, a single FITS file can contain multiple tables. FITS files usually have a .fits or .fit extension. We think FITS is one of the best ways to save tables due to its widespread support and mature, stable standard.

**PDS binary tables**

Many tabular data products in the PDS have ad-hoc structures they describe in external metadata. Standards differ between PDS3 and PDS4. In PDS3, structures can be defined in either their attached or detached PDS3 labels, or in an arbitrary number of distinct format (.fmt) files. In PDS4, binary table structure must be completely defined in a file's detached XML (.xml) label. Common extensions for these files include .dat and .tab.

**SQL databases**

**TODO: maybe skip this?**

**Parquet**

Parquet is a newer tabular interchange format that has seen wide adoption in industry and is increasingly common in scientific contexts. It is a _columnar_ format, which means that every field is stored in a distinct area and can be both compressed and readily accessed individually, which makes it very efficient for many purposes. We think Parquet is also an excellent choice for tabular data, especially very large tables that you don't want to load into memory all at once.

**general-purpose data formats**

Finally, while this category is much to broad to detail, it's worth noting that tables can also be represented in structured data formats that aren't specialized for tables, like Javascript Object Notation (JSON) and Extended Markup Language (XML). (In fact, Excel files rely in part on a compressed and modified version of XML!) Features of programming languages that save in-memory objects to disk, like Python `pickle` files or MATLAB .mat files, can similarly be used to store tables -- but then they can only be opened in that programming language! We don't recommend doing this unless you have a really good reason to.

**TODO: maybe something about headers?**


### Working with tables in Python

There are many packages for working with tabular data in Python. `pandas` is by far the most common, and it's what we'll mostly use in this book. `pandas` has built-in support for reading and writing a wide variety of table formats, but not all, so you'll sometimes need to use a helper package to load data into `pandas`. For instance, `pandas` can't read FITS tables, so you'll need to go through a specialty FITS library like `astropy.io.fits` or `fitsio`. Similarly, to read tables described in PDS metadata, you'll need to use a library like `pdr` or `pds4-tools`.

Also, as you saw in the previous lesson, people often compress table files 'monolithically', wrapping the whole file at once in a compression format like gzip. Some packages can decompress files like this automatically, but most can't, so you'll often need to decompress table files before you can use them.

`pandas` is very, very powerful; however, it has many features that don't follow a common idiom, so it needs to be used with care. Let's move on to some basic ways to use `pandas`. We'll use the Bright Star Catalog as our sample data.

In [194]:
import pandas as pd

# the BSC 'catalog' file has no file extension. However, if you open 
# it up in a text editor, you'll quickly see that:
# 1. it is a text table, and
# 2. it has no delimiter characters.
# this means that it is a fixed-width file. 
# you'll also notice that a lot of the fields appear to run together,
# which makes it somewhat hard to read -- both for humans and for
# pandas. let's see what happens if we just use the pandas
# read_fwf function, which attempts to read a FWF by inferring
# the width of each field. The header=None argument tells pandas
# that the table has no column headers.

bsc_take_1 = pd.read_fwf('bright_star_directory/catalog', header=None)
bsc_take_1

0                    1                2     3         4   \
0       1           BD+44 4550          3 36042  46.0       NaN   
1       2           BD-01 4525          6128569   NaN       NaN   
2       3  33    PscBD-06 6357    281285721002I   NaN      Var?   
3       4  86    PegBD+12 5063     87 917012004   NaN       NaN   
4       5           BD+57 2865        123 21085  61.0  V640 Cas   
...   ...                  ...              ...   ...       ...   
9105  106           CP-73 2346       5233255629   NaN       NaN   
9106  107           BD+33 4828   5239 536222002   NaN       NaN   
9107  108           CP-72 2800   52532556311001   NaN       NaN   
9108  109           BD+25 5068  5276 73731    I  42.0       NaN   
9109  110           BD+60 2667       5289 10962   NaN  V567 Cas   

                                              5     6     7     8      9   \
0     000001.1+444022000509.9+451345114.44-16.88  6.70  0.07  0.08    NaN   
1     235956.2-010330000503.8-003011 98.33-61.14  6.29  1.10  1.02    NaN   
2     000013.0-061601000520.1-054227 93.75-65.93  4.61  1.04  0.89  +0.54   
3     000033.8+125023000542.0+132346106.19-47.98  5.51  0.90   NaN    NaN   
4     000101.8+575245000616.0+582612117.03-03.92  5.96  0.67  0.20    NaN   
...                                          ...   ...   ...   ...    ...   
9105  235926.8-732712000430.7-725352307.68-43.80  7.31  0.44  0.01    NaN   
9106  235939.2+340602000453.8+343935112.17-27.24  6.12  0.62  0.09    NaN   
9107  235937.0-715936000441.3-712613308.18-45.21  5.59 -0.12 -0.42    NaN   
9108  235947.1+260533000456.0+263856110.22-35.07  6.25  1.40  1.59    NaN   
9109  235955.9+604526000506.2+611851117.40-01.06  5.80 -0.09 -0.32    NaN   

                10                                    11      12   13  
0             A1Vn  -0.012-0.018      -018      195  4.2  21.6AC    3  
1              gG9               +0.045-0.060      +014V     NaN  NaN  
2     K0IIIbCN-0.5  -0.009+0.089 +.014-006SB1O < 17  2.5     0.0   3*  
3            G5III              +0.045-0.012      -002V?     NaN  NaN  
4              G5V  +0.263+0.030 +.047-012V          0.8     1.4    *  
...            ...                                   ...     ...  ...  
9105           F2V                +0.010-0.054      +008     NaN  NaN  
9106           G2V               +0.772+0.089 +.035+004V     NaN  NaN  
9107        B8IV-V               +0.028-0.014      -003V     NaN  NaN  
9108        K4IIIb  +0.110-0.012      -005           4.5    17.5  NaN  
9109     B8IVpHgMn       +0.015+0.005      +014V      50     NaN    *  

[9110 rows x 14 columns]

In [195]:
# Ok, that looks _sort of_ reasonable. We can validate it by opening the specification of the table
# in bright_star_catalog/ReadMe in a text editor...
# And, unfortunately, if you scroll down to line 77, "Byte-by-byte Description of file",
# you'll see that it's not correct. The specification gives over 50 columns, while pandas detected
# only 14:
bsc_take_1.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int64')

In [228]:
# so, we have a couple of options here. If you take a look at the read_fwf() documentation here,
# https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html,
# you'll see that you can pass a list of column specifications to read_fwf() in its colspecs argument.
# however, we'd have to type all of those in, which is doable, but doesn't sound like much fun.
# The easy direct download we used last time deceived us.

In [217]:
# Let's, instead, try to get this into pandas another way.
# CNRS's Vizier service offers access to many complete catalogs. 
# Let's see if it's got the BSC.
from astroquery.vizier import Vizier

catalogs = Vizier.find_catalogs('Bright Star Catalogue')

In [219]:
# ok, it's got 19 catalogs related to that search! Let's take a look at which specific one we want:
{
    c: r.description for c, r in catalogs.items()
}

{'I/44': 'Second Cat of Fundamental Stars (SPF2) (Baturina+ 1986)',
 'I/45': 'Catalogue de Zimmerman (Zimmerman 1948)',
 'I/206': 'Bright Stars Supplement to PPM (Bastian+ 1993)',
 'I/309': '5969 Southern Reference Stars and 726 Bright stars (Konin+ 1983)',
 'I/328': 'Catalogue of bright IDS stars (Lipaeva+, 2014)',
 'II/80': 'Homogeneous Photometry Bright Stars on DDO System (McClure+ 1981)',
 'II/86': 'UV Bright-Star Spectrophotometric Supplement (Macau-Hercot+ 1978)',
 'III/39A': 'UV Bright Star Spectrophotometric Catalog (Jamar+, 1976)',
 'III/282': 'CoRoT Bright Stars Catalogue with variability classes (Baglin+, 2015)',
 'V/36B': 'Supplement to the Bright Star Catalogue (Hoffleit+ 1983)',
 'V/50': 'Bright Star Catalogue, 5th Revised Ed. (Hoffleit+, 1991)',
 'V/53A': 'Catalogue of the Brightest Stars (Ochsenbein+ 1988)',
 'J/ApJS/155/175': 'MK Classification of Bright Star Supplement (Abt, 2004)',
 'J/A+A/392/971': 'Catalogue of bright YSO candidates in ISOGAL (Felli+, 2002)',
 'J/

In [236]:
# looks like 'V/50' is our target. Let's go ahead and download the whole thing from Vizier.
# by default, Vizier will only return 50 rows, and we want the whole table, so let's 
# make a new Vizier object with changed settings:
big_vizier_fetcher = Vizier(row_limit=99999)
tables = big_vizier_fetcher.get_catalogs([catalogs['V/50']])
tables

TableList with 2 tables:
	'0:V/50/catalog' with 11 column(s) and 9110 row(s) 
	'1:V/50/notes' with 4 column(s) and 9190 row(s) 

In [237]:
# now we've got the catalog _and_ the notes. let's look at the catalog.
tables[0]

<Table length=9110>
  HR     Name     HD    ADS   VarID    RAJ2000    DEJ2000    Vmag    B-V      SpType    NoteFlag
                                                             mag     mag                        
int16   str10   int32   str5   str9     str10       str9   float32 float32    str20       str1  
----- --------- ------ ----- -------- ---------- --------- ------- ------- ------------ --------
    1                3    46          00 05 09.9 +45 13 45    6.70    0.07         A1Vn         
    2                6                00 05 03.8 -00 30 11    6.29    1.10          gG9         
    3 33    Psc     28           Var? 00 05 20.1 -05 42 27    4.61    1.04 K0IIIbCN-0.5        *
    4 86    Peg     87                00 05 42.0 +13 23 46    5.51    0.90        G5III         
    5              123    61 V640 Cas 00 06 16.0 +58 26 12    5.96    0.67          G5V        *
    6              142                00 06 19.0 -49 04 30    5.70    0.52         G1IV        *
    7 10    Cas    144                00 06 26.5 +64 11 46    5.59   -0.03        B9III        *
    8              166    69       33 00 06 36.8 +29 01 17    6.13    0.75          K0V        *
    9              203                00 06 50.1 -23 06 27    6.18    0.38          A7V         
   10              256                00 07 18.2 -17 23 11    6.19    0.14         A6Vn        *
   11              315           Var? 00 07 44.1 -02 32 56    6.43   -0.14     B8IIIpSi        *
   12              319    89       46 00 07 46.8 -22 30 32    5.94    0.14        A2Vp:        *
   13              344                00 08 03.5 -33 31 46    5.68    1.12        K1III         
   14              352         AP Psc 00 08 12.1 -02 26 52    6.07    1.38      K2III+F        *
   15 21Alp And    358    94  Alp And 00 08 23.3 +29 05 26    2.06   -0.11    B8IVpMnHg        *
   16              360                00 08 17.4 -08 49 26    5.99    1.04          gG8         
   17              400                00 08 41.0 +36 37 36    6.19    0.48         F8IV         
   18              402             51 00 08 33.4 -17 34 39    6.06    1.67        M0III        *
   19              417                00 08 52.2 +25 27 46    6.23    0.97        K0III         
   20              431   102          00 09 20.2 +79 42 53    6.01    0.19         A7IV        *
   21 11Bet Cas    432   107  Bet Cas 00 09 10.7 +59 08 59    2.27    0.34     F2III-IV        *
   22 87    Peg    448                00 09 02.4 +18 12 43    5.53    1.04        G9III         
   23              469                00 09 02.4 -54 00 07    6.33    0.74         G4IV        *
  ...       ...    ...   ...      ...        ...       ...     ...     ...          ...      ...
 9088 85    Peg 224930 17175    14809 00 02 10.2 +27 04 55    5.75    0.67     G5VbFe-2        *
 9089 30    Psc 224935         YY Psc 00 01 57.6 -06 00 51    4.41    1.63        M3III        *
 9090           224960          W Cet 00 02 07.3 -14 40 34    7.10    1.80        S7.3e        *
 9091   Zet Scl 224990                00 02 19.9 -29 43 13    5.01   -0.15        B4III        *
 9092 31    Psc 224995                00 02 24.2 +08 57 25    6.32    0.18          A6V         
 9093 32    Psc 225003                00 02 29.7 +08 29 08    5.63    0.29          F0V        *
 9094           225009     1          00 02 36.1 +66 05 56    5.86    1.09        G8III        *
 9095           225045                00 02 57.6 -20 02 46    6.25    0.53          F6V         
 9096           225069                00 03 07.7 -24 08 43    6.44    1.18           G5         
 9097           225094       V639 Cas 00 03 25.7 +63 38 31    6.24    0.33         B3Ia        *
 9098  2    Cet 225132                00 03 44.4 -17 20 10    4.55   -0.05       B9.5Vn         
 9099           225136                00 03 51.9 +66 42 44    6.29    1.67        M4III         
 9100  9    Cas 225180                00 04 13.6 +62 17 16    5.88    0.30        A1III         
 91

In [263]:
# this doesn't have quite as many columns as the 'full' version, but they're separated correctly,
# and we don't need most of that metadata. 
# you'll also note that astroquery.vizier returned this as an astropy Table object, but we'd rather
# work with it in pandas. astropy Tables can be easily converted to pandas, so let's do that:
bsc = tables[0].to_pandas()
bsc

HR       Name      HD ADS     VarID     RAJ2000    DEJ2000  Vmag  \
0        1                  3  46            00 05 09.9  +45 13 45  6.70   
1        2                  6                00 05 03.8  -00 30 11  6.29   
2        3  33    Psc      28          Var?  00 05 20.1  -05 42 27  4.61   
3        4  86    Peg      87                00 05 42.0  +13 23 46  5.51   
4        5                123  61  V640 Cas  00 06 16.0  +58 26 12  5.96   
...    ...        ...     ...  ..       ...         ...        ...   ...   
9105  9106             225233                00 04 30.7  -72 53 52  7.31   
9106  9107             225239                00 04 53.8  +34 39 35  6.12   
9107  9108             225253                00 04 41.3  -71 26 13  5.59   
9108  9109             225276  42            00 04 56.0  +26 38 56  6.25   
9109  9110             225289      V567 Cas  00 05 06.2  +61 18 51  5.80   

       B-V        SpType NoteFlag  
0     0.07          A1Vn           
1     1.10           gG9           
2     1.04  K0IIIbCN-0.5        *  
3     0.90         G5III           
4     0.67           G5V        *  
...    ...           ...      ...  
9105  0.44           F2V           
9106  0.62           G2V           
9107 -0.12        B8IV-V           
9108  1.40        K4IIIb           
9109 -0.09     B8IVpHgMn        *  

[9110 rows x 11 columns]

In [264]:
# that's more like it! now, to prevent us from having to fetch it again,
# let's write it out in a format pandas will be able to understand more easily --
# a simple CSV file.
# (the index=None argument means 'don't write the index as a separate column'.)
bsc.to_csv('bright_star_directory/catalog.csv', index=None)

In [298]:
# now let's verify that we can read it in again:
bsc_in = pd.read_csv('bright_star_directory/catalog.csv')
bsc_in

HR       Name        HD   ADS     VarID     RAJ2000    DEJ2000  Vmag  \
0        1        NaN       3.0  46.0       NaN  00 05 09.9  +45 13 45  6.70   
1        2        NaN       6.0   NaN       NaN  00 05 03.8  -00 30 11  6.29   
2        3  33    Psc      28.0   NaN      Var?  00 05 20.1  -05 42 27  4.61   
3        4  86    Peg      87.0   NaN       NaN  00 05 42.0  +13 23 46  5.51   
4        5        NaN     123.0  61.0  V640 Cas  00 06 16.0  +58 26 12  5.96   
...    ...        ...       ...   ...       ...         ...        ...   ...   
9105  9106        NaN  225233.0   NaN       NaN  00 04 30.7  -72 53 52  7.31   
9106  9107        NaN  225239.0   NaN       NaN  00 04 53.8  +34 39 35  6.12   
9107  9108        NaN  225253.0   NaN       NaN  00 04 41.3  -71 26 13  5.59   
9108  9109        NaN  225276.0  42.0       NaN  00 04 56.0  +26 38 56  6.25   
9109  9110        NaN  225289.0   NaN  V567 Cas  00 05 06.2  +61 18 51  5.80   

       B-V        SpType NoteFlag  
0     0.07          A1Vn      NaN  
1     1.10           gG9      NaN  
2     1.04  K0IIIbCN-0.5        *  
3     0.90         G5III      NaN  
4     0.67           G5V        *  
...    ...           ...      ...  
9105  0.44           F2V      NaN  
9106  0.62           G2V      NaN  
9107 -0.12        B8IV-V      NaN  
9108  1.40        K4IIIb      NaN  
9109 -0.09     B8IVpHgMn        *  

[9110 rows x 11 columns]

In [255]:
# Great. It looks the same, with one notable exception: it reinterpreted some
# of the columns as numbers, which also caused it to fill in blank spaces with NaNs. 
# This is in fact a very good thing! for instance, if we'd wanted to look at all the
# stars with Double Star Catalog designation (ADS) < 50, and had tried to do that on the 
# original table, we would have gotten an error, because Vizier specified that column
# as a string.

In [266]:
# ok, so what can we do with this object?
# First, a little vocab: this object is called a DataFrame. 
# This is one of the two basic pandas types. The other basic pandas type
# is a Series. Every field/column in a DataFrame is a Series:
type(bsc_in), type(bsc_in['RAJ2000'])

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [273]:
# like numpy, pandas has a lot of tools for accessing elements of a table,
# but it works differently, principally because rows and columns can have
# names, not just numbers.

# pandas's core tools for this are called _indexers_, and it has three of them:
# .at, .loc, and .iloc. .at is rarely used and we will ignore it; we will mostly 
# discuss .loc here.

# .loc fetches one or more elements by name: index name(s) first, column name(s) second.
# Like numpy, pandas uses ':' as a placeholder, and you don't have to give it both
# index and column. Some examples:

# this is the visual magnitude (Vmag) of stars 3000-3010:
bsc_in.loc[3000:3010, 'Vmag']

3000    6.40
3001    5.17
3002    4.88
3003    5.62
3004    6.57
3005    6.43
3006    5.80
3007    5.30
3008    6.89
3009    6.07
3010    5.88
Name: Vmag, dtype: float64

In [269]:
# this is everything in the 3000th row:
bsc_in.loc[3000]

HR                3001
Name               NaN
HD             62712.0
ADS                NaN
VarID              NaN
RAJ2000     07 43 42.9
DEJ2000      -38 12 07
Vmag               6.4
B-V              -0.16
SpType          B9VpSi
NoteFlag             *
Name: 3000, dtype: object

In [270]:
# this is the Vmag of every star:
bsc_in.loc[:, 'Vmag']

0       6.70
1       6.29
2       4.61
3       5.51
4       5.96
        ... 
9105    7.31
9106    6.12
9107    5.59
9108    6.25
9109    5.80
Name: Vmag, Length: 9110, dtype: float64

In [271]:
# simply using slice notation right on the dataframe is an alias for .loc[:, column_name]:
bsc_in['Vmag']

0       6.70
1       6.29
2       4.61
3       5.51
4       5.96
        ... 
9105    7.31
9106    6.12
9107    5.59
9108    6.25
9109    5.80
Name: Vmag, Length: 9110, dtype: float64

In [275]:
# you'll note that these last few gave Series objects rather than DataFrame objects.
# this is because we only got a single row or column at once. It's possible to slice
# a whole dataframe out of a dataframe. Because the columns have string names rather
# than numbers, you can do this by passing a list. Here is the vmag and right ascension
# of stars 30-40, presented as a dataframe:
bsc_in.loc[30:40, ['Vmag', 'RAJ2000']]

Vmag     RAJ2000
30  5.85  00 10 42.8
31  6.64  00 10 38.6
32  4.89  00 11 15.9
33  5.41  00 11 34.4
34  5.25  00 11 44.0
35  6.16  00 11 59.1
36  5.25  00 12 10.0
37  6.73  00 12 50.4
38  2.83  00 13 14.2
39  6.30  00 13 24.0
40  5.72  00 13 30.8

In [279]:
# like numpy arrays, you can select elements of a DataFrame that meet some special condition.
# the easiest way to do that is by defining a logical predicate. An expression like this
# produces a boolean Series giving us only very bright stars with Vmag < 2:
bright_predicate = bsc_in['Vmag'] < 2
bright_predicate

0       False
1       False
2       False
3       False
4       False
        ...  
9105    False
9106    False
9107    False
9108    False
9109    False
Name: Vmag, Length: 9110, dtype: bool

In [281]:
# we can then pass that Series to .loc in order to select all the rows
# of the DataFrame for which that condition is true:
bright = bsc_in.loc[bright_predicate]
bright

HR        Name        HD      ADS     VarID     RAJ2000    DEJ2000  \
471    472     Alp Eri   10144.0      NaN       Var  01 37 42.9  -57 14 12   
1016  1017   33Alp Per   20902.0      NaN      1125  03 24 19.4  +49 51 40   
1457  1457   87Alp Tau   29139.0   3321.0   Alp Tau  04 35 55.2  +16 30 33   
1707  1708   13Alp Aur   34029.0   3841.0      1897  05 16 41.4  +45 59 53   
1712  1713   19Bet Ori   34085.0   3823.0      1882  05 14 32.3  -08 12 06   
1789  1790   24Gam Ori   35468.0      NaN      1972  05 25 07.9  +06 20 59   
1790  1791  112Bet Tau   35497.0      NaN       NaN  05 26 17.5  +28 36 27   
1902  1903   46Eps Ori   37128.0      NaN   Eps Ori  05 36 12.8  -01 12 07   
2060  2061   58Alp Ori   39801.0   4506.0   Alp Ori  05 55 10.3  +07 24 25   
2087  2088   34Bet Aur   40183.0   4556.0   Bet Aur  05 59 31.7  +44 56 51   
2293  2294    2Bet CMa   44743.0      NaN   Bet CMa  06 22 42.0  -17 57 21   
2325  2326     Alp Car   45348.0      NaN       NaN  06 23 57.1  -52 41 45   
2420  2421   24Gam Gem   47105.0      NaN       NaN  06 37 42.7  +16 23 57   
2490  2491    9Alp CMa   48915.0   5423.0       NaN  06 45 08.9  -16 42 58   
2617  2618   21Eps CMa   52089.0   5654.0       NaN  06 58 37.5  -28 58 20   
2692  2693   25Del CMa   54605.0      NaN      3424  07 08 23.5  -26 23 36   
2890  2891   66Alp Gem   60179.0   6175.0    YY Gem  07 34 36.0  +31 53 18   
2942  2943   10Alp CMi   61421.0   6251.0      3672  07 39 18.1  +05 13 30   
2989  2990   78Bet Gem   62509.0   6335.0      3712  07 45 18.9  +28 01 34   
3206  3207     Gam2Vel   68273.0      NaN  Gam2 Vel  08 09 32.0  -47 20 12   
3306  3307     Eps Car   71129.0      NaN      4058  08 22 30.8  -59 30 35   
3484  3485     Del Vel   74956.0      NaN       NaN  08 44 42.2  -54 42 30   
3684  3685     Bet Car   80007.0      NaN       NaN  09 13 12.0  -69 43 02   
3747  3748   30Alp Hya   81797.0      NaN      4496  09 27 35.2  -08 39 31   
3981  3982   32Alp Leo   87901.0   7654.0      4750  10 08 22.3  +11 58 02   
4300  4301   50Alp UMa   95689.0   8035.0      5070  11 03 43.7  +61 45 03   
4729  4730     Alp1Cru  108248.0      NaN       NaN  12 26 35.9  -63 05 57   
4730  4731     Alp2Cru  108249.0      NaN       NaN  12 26 36.5  -63 05 58   
4762  4763     Gam Cru  108903.0      NaN      5672  12 31 09.9  -57 06 48   
4852  4853     Bet Cru  111123.0      NaN   Bet Cru  12 47 43.2  -59 41 19   
4904  4905   77Eps UMa  112185.0      NaN   Eps UMa  12 54 01.7  +55 57 35   
5055  5056   67Alp Vir  116658.0      NaN   Alp Vir  13 25 11.6  -11 09 41   
5190  5191   85Eta UMa  120315.0      NaN      6450  13 47 32.4  +49 18 48   
5266  5267     Bet Cen  122451.0      NaN   Bet Cen  14 03 49.4  -60 22 23   
5339  5340   16Alp Boo  124897.0      NaN      6603  14 15 39.7  +19 10 57   
5458  5459     Alp1Cen  128620.0      NaN       NaN  14 39 35.9  -60 50 07   
5459  5460     Alp2Cen  128621.0      NaN       NaN  14 39 36.1  -60 50 08   
6133  6134   21Alp Sco  148478.0  10074.0   Alp Sco  16 29 24.4  -26 25 55   
6216  6217     Alp TrA  150798.0      NaN       NaN  16 48 39.9  -69 01 40   
6527  6527   35Lam Sco  158926.0      NaN   Lam Sco  17 33 36.5  -37 06 14   
6552  6553     The Sco  159532.0      NaN      9233  17 37 19.2  -42 59 52   
6878  6879   20Eps Sgr  169022.0      NaN       NaN  18 24 10.3  -34 23 05   
7000  7001    3Alp Lyr  172167.0  11510.0   Alp Lyr  18 36 56.3  +38 47 01   
7556  7557   53Alp Aql  187642.0  13009.0       NaN  19 50 47.0  +08 52 06   
7789  7790     Alp Pav  193924.0      NaN     13060  20 25 38.9  -56 44 06   
7923  7924   50Alp Cyg  197345.0  14172.0   Alp Cyg  20 41 25.9  +45 16 49   
8424  8425     Alp Gru  209952.0      NaN     14040  22 08 14.0  -46 57 40   
8728  8728   24Alp PsA  216956.0      NaN     14372  22 57 39.1  -29 37 20   

      Vmag   B-V           SpType NoteFlag  
471   0.46 -0.16            B3Vpe        *  
1016  1.79  0.48             F5Ib        *  
1457  0.85  1.54           K5+III        *  
1707 

In [284]:
# like arrays, the values in DataFrames can be easily plotted with matplotlib.
# for instance, to make a scatter plot of Vmag vs. color (B-V):
plt.scatter(bsc_in['Vmag'], bsc_in['B-V'])

In [302]:
# like arrays, you can assign values to particular elements of a DataFrame,
# and you can do operations on big swaths of a DataFrame at once.
# you'll note that there's some unnecessary padding in the 'Name' field:
bsc_in.loc[2, 'Name']

'33    Psc'

In [305]:
# let's trim all that using a simple regex that will truncate all sequences of more than one space. 
bsc_in['Name'] = bsc_in['Name'].str.replace('  +', ' ', regex=True)
bsc_in.loc[2, 'Name']

'33 Psc'

In [311]:
# unlike arrays, you can also just add new columns willy-nilly. Vmag is logarithmic in base ~2.512, so 
# if you wanted a linear version of it for some calculation, you could do this:
bsc_in['Vmag_exp'] = 2.512 ** bsc_in['Vmag']
bsc_in['Vmag_exp']

0       478.775099
1       328.188610
2        69.837795
3       159.995655
4       242.168151
           ...    
9105    839.737470
9106    280.620999
9107    172.230380
9108    316.317136
9109    208.984407
Name: Vmag_exp, Length: 9110, dtype: float64

In [313]:
# and we don't really want it, so let's take a look at how we can easily drop that column:
bsc_in = bsc_in.drop(columns='Vmag_exp')
bsc_in

HR    Name        HD   ADS     VarID     RAJ2000    DEJ2000  Vmag  \
0        1     NaN       3.0  46.0       NaN  00 05 09.9  +45 13 45  6.70   
1        2     NaN       6.0   NaN       NaN  00 05 03.8  -00 30 11  6.29   
2        3  33 Psc      28.0   NaN      Var?  00 05 20.1  -05 42 27  4.61   
3        4  86 Peg      87.0   NaN       NaN  00 05 42.0  +13 23 46  5.51   
4        5     NaN     123.0  61.0  V640 Cas  00 06 16.0  +58 26 12  5.96   
...    ...     ...       ...   ...       ...         ...        ...   ...   
9105  9106     NaN  225233.0   NaN       NaN  00 04 30.7  -72 53 52  7.31   
9106  9107     NaN  225239.0   NaN       NaN  00 04 53.8  +34 39 35  6.12   
9107  9108     NaN  225253.0   NaN       NaN  00 04 41.3  -71 26 13  5.59   
9108  9109     NaN  225276.0  42.0       NaN  00 04 56.0  +26 38 56  6.25   
9109  9110     NaN  225289.0   NaN  V567 Cas  00 05 06.2  +61 18 51  5.80   

       B-V        SpType NoteFlag  
0     0.07          A1Vn      NaN  
1     1.10           gG9      NaN  
2     1.04  K0IIIbCN-0.5        *  
3     0.90         G5III      NaN  
4     0.67           G5V        *  
...    ...           ...      ...  
9105  0.44           F2V      NaN  
9106  0.62           G2V      NaN  
9107 -0.12        B8IV-V      NaN  
9108  1.40        K4IIIb      NaN  
9109 -0.09     B8IVpHgMn        *  

[9110 rows x 11 columns]

In [330]:
# you can also drop rows. There are a few entries in the BSC that don't have actual
# coordinates. Let's clean them up quickly. Note that the '~' means 'not', so we're 
# saying: 'get rid of all the rows that don't have a real RAJ2000 value'.
bsc_in = bsc_in.loc[~(bsc['RAJ2000'] == '')]
# after you do this sort of thing, it's usually a good idea to copy the dataframe and reset the
# index -- otherwise you can get confusing errors. (There are cases where this isn't
# true, of course, but it's a good rule of thumb.) This is the easiest way to do it:
bsc_in = bsc_in.copy().reset_index(drop=True)

In [332]:
# there's one more thing we should do before we move on. The BSC gives RA and DEC
# in sexigesimal notation. This is all well and good, but can be hard for general-purpose
# tools to work with, because they don't usually understand this notation. Hence this error:
bsc_in.loc[(bsc_in['RAJ2000'] < 20) & (bsc_in['DEJ2000'] > 0)]

TypeError: '<' not supported between instances of 'str' and 'int'

In [349]:
# fortunately, astropy _does_ understand this notation, and we can use it to convert these
# from sexigesimal to decimal. The Angle object from astropy.coordinates is our helper here.
# note that you have to specify the units, or astropy will be unhappy.
from astropy.coordinates import Angle
ra0 = Angle(bsc_in.loc[0, 'RAJ2000'], unit='hour')
# astropy parses and prints it nicely:
ra0

<Angle 0.08608333 hourangle>

In [361]:
# and then you can convert it from hour-minute-second to decimal degrees:
ra0_decimal = ra0.degree
ra0_decimal

1.2912499999999998

In [362]:
# that's all well and good for a single value -- but you can even pass the entire
# Series at once...
ra_angles = Angle(bsc_in['RAJ2000'], unit='hour')
ra_angles

<Angle [0.08608333, 0.08438889, 0.08891667, ..., 0.07813889, 0.08222222,
        0.08505556] hourangle>

In [363]:
# and convert it all to decimal at once!
ra_decimal = ra_angles.degree
ra_decimal

array([1.29125   , 1.26583333, 1.33375   , ..., 1.17208333, 1.23333333,
       1.27583333])

In [368]:
# let's do the same thing with declination, which is in degree-minute-second
# rather than hour-minute-second:
dec_angle = Angle(bsc_in['DEJ2000'], unit='deg')
dec_angle

<Angle [ 45.22916667,  -0.50305556,  -5.7075    , ..., -71.43694444,
         26.64888889,  61.31416667] deg>

In [371]:
dec_decimal = dec_angle.degree
dec_decimal

array([ 45.22916667,  -0.50305556,  -5.7075    , ..., -71.43694444,
        26.64888889,  61.31416667])

In [373]:
# now we can go ahead and replace the ra/dec strings in the dataframe
# with our decimal numbers.
bsc_in['RAJ2000'] = ra_decimal
bsc_in['DEJ2000'] = dec_decimal

In [ ]:
# and you'll find that our earlier expression will work: